<<<<<<< HEAD
markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://yonsm.tk
name: Yonsm.NET
author: Yonsm
pygments: true
safe: true
paginate: 16
auto: true

=======
baseurl: /
>>>>>>> b6edc1ce4e940725222f47b302c6bc2dc3486d74
